# Generated by Django 2.0.6 on 2018-09-08 06:20

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', markdownx.models.MarkdownxField()),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('attach', models.FileField(blank=True, upload_to='')),
                ('is_display', models.BooleanField(default=0)),
                ('view_cnt', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
